org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=/usr/lib/jvm/zulu-17-amd64

# Minecraft & Forge
minecraftVersion = 1.20.1
forgeVersion = 47.4.0
javaVersion = 17

# Dependency versions
jeiVersion = 15.20.0.112
reiVersion = 12.1.785
clothVersion = 11.0.99
archVersion = 9.0.8

# Mod Properties
mod_id = luoyu
mod_name = Good Entity
mod_license = MIT
mod_version = 0.0.1-alpha
mod_group_id = net.luoyu.goodentity
mod_authors = LuoYu
mod_description = An addon mod for the Changed Minecraft Mod, adding new entities, variants, and abilities.

systemProp.javax.net.debug=ssl
