modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/LuoYuMC/good_entity_mod/issues"

[[mods]]
modId="goodentity"
version="0.0.1-alpha"
displayName="Good Entity"
displayURL="https://github.com/LuoYuMC/good_entity_mod"
authors="LuoYu"
description="An addon mod for the Changed Minecraft Mod, adding new entities, variants, and abilities."
logoFile=""

[[dependencies.goodentity]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.goodentity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.goodentity]]
    modId="changed"
    mandatory=true
    versionRange="[0.15.7,)"
    ordering="AFTER"
    side="BOTH"
